export const mockData = {
  "pid": "",
  "eid": "13b3dc89-98d3-4c29-b3f7-831ec564d46d",
  "name": "国泰君安证券股份有限公司",
  "parent": true,
  "id": "国泰君安证券股份有限公司",
  "children": [
    {
      "classType": "E-01",
      "desc": "法定代表人",
      "id": "法定代表人",
      "collapsed": false,
      "desType": "up",
      "total": 1,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "",
          "pid": "",
          "name": "贺青",
          "id": "贺青",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-02",
      "desc": "实际控制人",
      "id": "实际控制人",
      "collapsed": false,
      "desType": "up",
      "total": 1,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "a56224ad-e6e3-4ddf-b5a3-4c639784dfe6",
          "pid": "",
          "name": "上海市国有资产监督管理委员会",
          "id": "上海市国有资产监督管理委员会",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "29%",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-03",
      "desc": "受益所有人",
      "id": "受益所有人",
      "collapsed": false,
      "desType": "up",
      "total": 24,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "",
          "pid": "",
          "name": "靳庆军",
          "id": "靳庆军",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "左志鹏",
          "id": "左志鹏",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "李港卫",
          "id": "李港卫",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "施德容",
          "id": "施德容",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "刘信义",
          "id": "刘信义",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "夏大慰",
          "id": "夏大慰",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "管蔚",
          "id": "管蔚",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "钟茂军",
          "id": "钟茂军",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "周浩",
          "id": "周浩",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "冯小东",
          "id": "冯小东",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-04",
      "desc": "股东",
      "id": "股东",
      "collapsed": true,
      "desType": "up",
      "total": 11,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "1cb85107-b315-457b-9c28-dc7769695f76",
          "pid": "",
          "name": "上海国有资产经营有限公司",
          "id": "上海国有资产经营有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "21.34%",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "417d61e4-be1d-11e6-8a4c-00163f00240b",
          "pid": "",
          "name": "香港中央结算（代理人）有限公司",
          "id": "香港中央结算（代理人）有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "15.62%",
          "hasChildren": false,
          "isHK": true
        },
        {
          "eid": "738bec65-db94-4858-8bdc-f158682a8270",
          "pid": "",
          "name": "上海国际集团有限公司",
          "id": "上海国际集团有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "7.66%",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "03bca8dd-7445-4c87-aee7-80613580f832",
          "pid": "",
          "name": "深圳市投资控股有限公司",
          "id": "深圳市投资控股有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "6.84%",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "ff4b7241-8cce-4317-abc6-5ae133e5b0c8",
          "pid": "",
          "name": "中国证券金融股份有限公司",
          "id": "中国证券金融股份有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "2.92%",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "394441fa-f50b-4b99-89c4-141ce74aeb1b",
          "pid": "",
          "name": "上海城投（集团）有限公司",
          "id": "上海城投（集团）有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "2.77%",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "2b91cfdb-63a1-4c14-b7cf-8cc7e77123a3",
          "pid": "",
          "name": "深圳能源集团股份有限公司",
          "id": "深圳能源集团股份有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "1.73%",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "08a32aee-be17-11e6-b97b-00163e014a2c",
          "pid": "",
          "name": "香港中央结算有限公司",
          "id": "香港中央结算有限公司",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "1.51%",
          "hasChildren": false,
          "isHK": true
        },
        {
          "eid": "",
          "pid": "",
          "name": "中国建设银行股份有限公司-国泰中证全指证券公司交易型开放式指数证券投资基金",
          "id": "中国建设银行股份有限公司-国泰中证全指证券公司交易型开放式指数证券投资基金",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "1.01%",
          "hasChildren": false,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "国泰君安证券股份有限公司回购专用证券账户",
          "id": "国泰君安证券股份有限公司回购专用证券账户",
          "collapsed": true,
          "desType": 'up',
          "positions": "",
          "percent": "1%",
          "hasChildren": false,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-05",
      "desc": "高管",
      "id": "高管",
      "collapsed": true,
      "desType": "up",
      "total": 24,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "",
          "pid": "",
          "name": "贺青",
          "id": "贺青",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事长",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "刘信义",
          "id": "刘信义",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "陈国钢",
          "id": "陈国钢",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "凌涛",
          "id": "凌涛",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "管蔚",
          "id": "管蔚",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "王松",
          "id": "王松",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "钟茂军",
          "id": "钟茂军",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "王文杰",
          "id": "王文杰",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "李港卫",
          "id": "李港卫",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "",
          "pid": "",
          "name": "靳庆军",
          "id": "靳庆军",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "董事",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-06",
      "desc": "对外投资",
      "id": "对外投资",
      "collapsed": true,
      "desType": "up",
      "total": 45,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "d8b1936a-f6ce-432d-9bbb-fd30d232cb23",
          "pid": "",
          "name": "上海国翔置业有限公司",
          "id": "上海国翔置业有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "75872188-e7fc-4d20-878a-aa4e3ba132a1",
          "pid": "",
          "name": "国泰君安证裕投资有限公司",
          "id": "国泰君安证裕投资有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "380988a2-d1ae-4653-96c2-028409763813",
          "pid": "",
          "name": "国泰君安期货有限公司",
          "id": "国泰君安期货有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "8c16e43f-f308-42f5-92e5-ce7bbbec47b2",
          "pid": "",
          "name": "上海国泰君安证券资产管理有限公司",
          "id": "上海国泰君安证券资产管理有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "beeeafdd-fdd9-48f6-a5fd-4f5bc9a6adc0",
          "pid": "",
          "name": "国泰君安创新投资有限公司",
          "id": "国泰君安创新投资有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "75f2aab5-d437-43dc-a25f-7234fe081f4e",
          "pid": "",
          "name": "上海证券有限责任公司",
          "id": "上海证券有限责任公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "24.99%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "dd93180c-5449-4d30-af49-d7019dbdee23",
          "pid": "",
          "name": "华安基金管理有限公司",
          "id": "华安基金管理有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "20%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "925c0f20-0fc1-4046-9769-16ce770eaa42",
          "pid": "",
          "name": "贵州富邦投资有限公司",
          "id": "贵州富邦投资有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "16.6667%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "305cb52e-600c-4dca-ae8a-a136ffca19eb",
          "pid": "",
          "name": "上海科创中心一期股权投资基金合伙企业（有限合伙）",
          "id": "上海科创中心一期股权投资基金合伙企业（有限合伙）",
          "collapsed": true,
          "desType": 'up',
          "percent": "15.3327%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "d13f7d40-bf74-44b1-9f2b-19c73a9e5e0e",
          "pid": "",
          "name": "上海科创中心股权投资基金管理有限公司",
          "id": "上海科创中心股权投资基金管理有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "13%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-07",
      "desc": "对外担保",
      "id": "对外担保",
      "collapsed": true,
      "desType": "up",
      "total": 4,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "",
          "pid": "",
          "name": "国泰君安控股有限公司",
          "id": "国泰君安控股有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": false,
          "isHK": false
        },
        {
          "eid": "75f2aab5-d437-43dc-a25f-7234fe081f4e",
          "pid": "",
          "name": "上海证券有限责任公司",
          "id": "上海证券有限责任公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "6201ea8e-be6d-11e6-8ca8-00163e014a2c",
          "pid": "",
          "name": "国泰君安金融控股有限公司",
          "id": "国泰君安金融控股有限公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": false,
          "isHK": true
        },
        {
          "eid": "",
          "pid": "",
          "name": "GUOTAIJUNANHOLDINGSLIMITED",
          "id": "GUOTAIJUNANHOLDINGSLIMITED",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": false,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-08",
      "desc": "分支机构",
      "id": "分支机构",
      "collapsed": true,
      "desType": "up",
      "total": 414,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "2cc85eb2-22d2-46c5-bc85-56b83509f63a",
          "pid": "",
          "name": "国泰君安证券股份有限公司天津青年路证券营业部",
          "id": "国泰君安证券股份有限公司天津青年路证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "f047c7e4-930c-4a5f-9640-120e9538e363",
          "pid": "",
          "name": "国泰君安证券股份有限公司天津新开路证券营业部",
          "id": "国泰君安证券股份有限公司天津新开路证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "ccf0cfa6-0b15-4509-9e3d-3c126304011e",
          "pid": "",
          "name": "国泰君安证券股份有限公司佛山南海大道证券营业部",
          "id": "国泰君安证券股份有限公司佛山南海大道证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "46ac89d2-b618-43f0-84de-560b61cb7da0",
          "pid": "",
          "name": "国泰君安证券股份有限公司北京光华路证券营业部",
          "id": "国泰君安证券股份有限公司北京光华路证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "9d8920ac-8740-488f-aecc-deacde04fdbd",
          "pid": "",
          "name": "国泰君安证券股份有限公司北京通州新华西街证券营业部",
          "id": "国泰君安证券股份有限公司北京通州新华西街证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "679e3b46-08c8-4660-a2e7-4470962d561f",
          "pid": "",
          "name": "国泰君安证券股份有限公司广州珠江新城证券营业部",
          "id": "国泰君安证券股份有限公司广州珠江新城证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "caa6dccc-7fab-4020-ba3f-5ccc8060f916",
          "pid": "",
          "name": "国泰君安证券股份有限公司廊坊广阳道证券营业部",
          "id": "国泰君安证券股份有限公司廊坊广阳道证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "60cf23d2-c960-4ccc-8df3-691f9a26f291",
          "pid": "",
          "name": "国泰君安证券股份有限公司广西分公司",
          "id": "国泰君安证券股份有限公司广西分公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "3ba6634a-694b-4dac-9ec6-513677382d63",
          "pid": "",
          "name": "国泰君安证券股份有限公司珠海景山路证券营业部",
          "id": "国泰君安证券股份有限公司珠海景山路证券营业部",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "eb051875-c841-4c68-90ce-46f94925fb46",
          "pid": "",
          "name": "国泰君安证券股份有限公司新疆分公司",
          "id": "国泰君安证券股份有限公司新疆分公司",
          "collapsed": true,
          "desType": 'up',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-09",
      "desc": "客户",
      "id": "客户",
      "collapsed": true,
      "desType": "down",
      "total": 5,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "36b9fad6-07ae-4f14-9685-5bb66ec63117",
          "pid": "",
          "name": "北京火谷网络科技股份有限公司",
          "id": "北京火谷网络科技股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "90de94d6-dd62-458c-b486-dcd80946c73a",
          "pid": "",
          "name": "广东三人行管理咨询股份有限公司",
          "id": "广东三人行管理咨询股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "cc990350-04fb-4ead-8f24-d8dc1e3412ff",
          "pid": "",
          "name": "易康云（北京）健康科技股份有限公司",
          "id": "易康云（北京）健康科技股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "20497a6c-5026-4fdc-a3f9-f805f469fd83",
          "pid": "",
          "name": "好买财富管理股份有限公司",
          "id": "好买财富管理股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "bfffeeae-80f5-4ef4-a62c-72b07e0b95d3",
          "pid": "",
          "name": "吉林市歌舞团文化传媒股份有限公司",
          "id": "吉林市歌舞团文化传媒股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-10",
      "desc": "供应商",
      "id": "供应商",
      "collapsed": true,
      "desType": "down",
      "total": 7,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "777a790d-d73c-4e71-88a9-9fc7393e729f",
          "pid": "",
          "name": "上海携宁计算机科技股份有限公司",
          "id": "上海携宁计算机科技股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "e377ecdf-be8b-46b8-9f10-8a5016b1e078",
          "pid": "",
          "name": "上海佳锐信息科技股份有限公司",
          "id": "上海佳锐信息科技股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "4916bccd-681e-4d57-be2d-7b29f9e5e37c",
          "pid": "",
          "name": "上海锐至信息技术股份有限公司",
          "id": "上海锐至信息技术股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "33636537-eab6-40c0-9a38-46bc3ebe1c70",
          "pid": "",
          "name": "上海功途教育科技股份有限公司",
          "id": "上海功途教育科技股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "c572138e-1fa5-4b7d-aad2-9f8971233b25",
          "pid": "",
          "name": "深圳市财富趋势科技股份有限公司",
          "id": "深圳市财富趋势科技股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "dc8bfb25-e678-430d-8137-9219df3170f8",
          "pid": "",
          "name": "海南财富无线信息技术股份有限公司",
          "id": "海南财富无线信息技术股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "4b4732fd-3280-49c6-90c7-7e41d76abca3",
          "pid": "",
          "name": "杭州时代银通软件股份有限公司",
          "id": "杭州时代银通软件股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-11",
      "desc": "历史对外投资",
      "id": "历史对外投资",
      "collapsed": true,
      "desType": "down",
      "total": 4,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "6a3707f9-1fb2-46ef-ab66-abf7b08a4943",
          "pid": "",
          "name": "南方风机股份有限公司",
          "id": "南方风机股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "4.95%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "462a477d-fce6-4945-93b9-458b7bd6aa57",
          "pid": "",
          "name": "湖南金源新材料股份有限公司",
          "id": "湖南金源新材料股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "1.4859%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "d03718f6-1c92-4bee-94a0-f7c792e15714",
          "pid": "",
          "name": "安徽省天然气开发股份有限公司",
          "id": "安徽省天然气开发股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "0.53%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "94abc9c8-378d-499e-af79-fb8e308e8058",
          "pid": "",
          "name": "中国神华能源股份有限公司",
          "id": "中国神华能源股份有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "0.08%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-12",
      "desc": "历史法定代表人",
      "id": "历史法定代表人",
      "collapsed": true,
      "desType": "down",
      "total": 1,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "",
          "pid": "",
          "name": "杨德红",
          "id": "杨德红",
          "collapsed": true,
          "desType": 'down',
          "percent": "",
          "positions": "",
          "hasChildren": false,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-13",
      "desc": "历史股东",
      "id": "历史股东",
      "collapsed": true,
      "desType": "down",
      "total": 2,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "c3fa5567-5966-4a46-bbbf-5412a087ff67",
          "pid": "",
          "name": "中国核工业集团有限公司",
          "id": "中国核工业集团有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "0.86%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "bc2a0cb6-4ee3-4cf7-8efd-e8a11a348c07",
          "pid": "",
          "name": "杭州市金融投资集团有限公司",
          "id": "杭州市金融投资集团有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "0.85%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    },
    {
      "classType": "E-14",
      "desc": "疑似控制企业",
      "id": "疑似控制企业",
      "collapsed": true,
      "desType": "down",
      "total": 215,
      "hiddenChildren": false,
      "children": [
        {
          "eid": "ec6fa22c-65b3-4717-a13a-7585334c3e39",
          "pid": "",
          "name": "镇江国君创投股权投资合伙企业（有限合伙）",
          "id": "镇江国君创投股权投资合伙企业（有限合伙）",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "e4da8a5f-4b96-4126-9ab1-9b1e45450136",
          "pid": "",
          "name": "上海国君创投隆鋆创业投资管理中心（有限合伙）",
          "id": "上海国君创投隆鋆创业投资管理中心（有限合伙）",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "e3741587-0e88-48c1-bf1c-843d156ca90d",
          "pid": "",
          "name": "上海国泰君安君彤投资管理有限公司",
          "id": "上海国泰君安君彤投资管理有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "d8b1936a-f6ce-432d-9bbb-fd30d232cb23",
          "pid": "",
          "name": "上海国翔置业有限公司",
          "id": "上海国翔置业有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "beeeafdd-fdd9-48f6-a5fd-4f5bc9a6adc0",
          "pid": "",
          "name": "国泰君安创新投资有限公司",
          "id": "国泰君安创新投资有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "b85e4953-8bc6-498b-a44d-7dfac5121cd6",
          "pid": "",
          "name": "广东国君共赢一号股权投资合伙企业（有限合伙）",
          "id": "广东国君共赢一号股权投资合伙企业（有限合伙）",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "af0f7f54-3826-4d5d-b1b2-5ee552a85385",
          "pid": "",
          "name": "上海千广投资管理中心（有限合伙）",
          "id": "上海千广投资管理中心（有限合伙）",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "aacadea7-ed33-425a-985d-d471c8233e79",
          "pid": "",
          "name": "上海国泰君安好景投资管理有限公司",
          "id": "上海国泰君安好景投资管理有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "a482b238-b47a-4693-abf0-c597f3d12ea5",
          "pid": "",
          "name": "上海国君创投隆祐创业投资管理中心（有限合伙）",
          "id": "上海国君创投隆祐创业投资管理中心（有限合伙）",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        },
        {
          "eid": "8c16e43f-f308-42f5-92e5-ce7bbbec47b2",
          "pid": "",
          "name": "上海国泰君安证券资产管理有限公司",
          "id": "上海国泰君安证券资产管理有限公司",
          "collapsed": true,
          "desType": 'down',
          "percent": "100%",
          "positions": "",
          "hasChildren": true,
          "isHK": false
        }
      ]
    }
  ]
}
