export default {
  nodes:[
    {
      "imgtype": "com",
      "num": 1,
      "basetype": "1",
      "name": "证通股份有限公司",
      "id": "I2xtd2KoRME"
    },
    {
      "imgtype": "com",
      "num": 2,
      "basetype": "1",
      "name": "财通证券股份有限公司",
      "id": "LPI65UoS103"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "永安期货股份有限公司",
      "id": "U70LNLlx2kJ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "国泰君安证券股份有限公司",
      "id": "TCgLa3axRa0"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "上海证券有限责任公司",
      "id": "TTsVVzhdhb0"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "吉林省艾斯克机电股份有限公司",
      "id": "6xbKhMe7BqE"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "广发证券股份有限公司",
      "id": "E8jD8W4h9nQ"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "孙树明",
      "id": "eN2zDr696r7Y"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "中证机构间报价系统股份有限公司",
      "id": "BkEqfjgJnJ"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "申建新",
      "id": "eTY9ThRVhpUJ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "浙江股权服务集团有限公司",
      "id": "UluONnT3ZgE"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "博时基金管理有限公司",
      "id": "CJGlwMN0EE"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "吉林利源精制股份有限公司",
      "id": "6NZ3qksi3rx"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "财通基金管理有限公司",
      "id": "T59LEFBJfuN"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "天弘基金管理有限公司",
      "id": "eDvj4QIrXhi3"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "宁波均胜电子股份有限公司",
      "id": "6P5ur46WNJ3"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "国泰君安期货有限公司",
      "id": "Ib2pEhALpf3"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "海通期货股份有限公司",
      "id": "3AlbTKjR33j"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "海通证券股份有限公司",
      "id": "IdLmpasckC0"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "大连优创液压股份有限公司",
      "id": "1FTTCDD8uFJ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "中国银河证券股份有限公司",
      "id": "CaD3Ax4bjx"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "中证丽泽置业（北京）有限责任公司",
      "id": "eVu0hPk6mvCJ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "华安基金管理有限公司",
      "id": "TkIzYdXtJ7E"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "申万宏源集团股份有限公司",
      "id": "Izto9m4ivXY"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "东北证券股份有限公司",
      "id": "kkXdAtmaXXj"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "北京仙果科技股份有限公司",
      "id": "7CXZjCRywcQ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "方正证券股份有限公司",
      "id": "JYpcStI4qyj"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "朱洪超",
      "id": "0uAsYwSke3m0"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "安徽源和堂药业股份有限公司",
      "id": "MTUd7ED2Wfx"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "吴承明",
      "id": "HsOq4AuS5mN"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "东方证券股份有限公司",
      "id": "3Be4t06jbPQ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "汇添富基金管理股份有限公司",
      "id": "IGW5A8HwkWx"
    }
  ],
  edges:[
    {
      "basetype": "line",
      "relation": "投资(40%)",
      "target": "T59LEFBJfuN",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资",
      "target": "Izto9m4ivXY",
      "source": "IdLmpasckC0"
    },
    {
      "basetype": "line",
      "relation": "投资(0.6622%)",
      "target": "BkEqfjgJnJ",
      "source": "3Be4t06jbPQ"
    },
    {
      "source": "T59LEFBJfuN",
      "relation": "董事",
      "target": "0uAsYwSke3m0",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资(1.1113%)",
      "target": "6NZ3qksi3rx",
      "source": "T59LEFBJfuN"
    },
    {
      "source": "E8jD8W4h9nQ",
      "relation": "总经理",
      "target": "eN2zDr696r7Y",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资(35.4118%)",
      "target": "IGW5A8HwkWx",
      "source": "3Be4t06jbPQ"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "CaD3Ax4bjx"
    },
    {
      "basetype": "line",
      "relation": "投资(1.7778%)",
      "target": "1FTTCDD8uFJ",
      "source": "JYpcStI4qyj"
    },
    {
      "basetype": "line",
      "relation": "投资",
      "target": "7CXZjCRywcQ",
      "source": "kkXdAtmaXXj"
    },
    {
      "basetype": "line",
      "relation": "投资(0.1371%)",
      "target": "MTUd7ED2Wfx",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资(1.0701%)",
      "target": "6NZ3qksi3rx",
      "source": "CJGlwMN0EE"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "IdLmpasckC0"
    },
    {
      "source": "HsOq4AuS5mN",
      "relation": "董事",
      "target": "I2xtd2KoRME",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资(2%)",
      "target": "I2xtd2KoRME",
      "source": "CJGlwMN0EE"
    },
    {
      "basetype": "line",
      "relation": "投资(2.2345%)",
      "target": "6P5ur46WNJ3",
      "source": "eDvj4QIrXhi3"
    },
    {
      "basetype": "line",
      "relation": "投资(8.8571%)",
      "target": "UluONnT3ZgE",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资",
      "target": "7CXZjCRywcQ",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资(0.6622%)",
      "target": "BkEqfjgJnJ",
      "source": "TCgLa3axRa0"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "eDvj4QIrXhi3"
    },
    {
      "basetype": "line",
      "relation": "投资(2.2222%)",
      "target": "1FTTCDD8uFJ",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资(16.5%)",
      "target": "eVu0hPk6mvCJ",
      "source": "CaD3Ax4bjx"
    },
    {
      "source": "eN2zDr696r7Y",
      "relation": "董事",
      "target": "BkEqfjgJnJ",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资",
      "target": "TTsVVzhdhb0",
      "source": "TCgLa3axRa0"
    },
    {
      "basetype": "line",
      "relation": "投资(2%)",
      "target": "I2xtd2KoRME",
      "source": "TkIzYdXtJ7E"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "E8jD8W4h9nQ"
    },
    {
      "basetype": "line",
      "relation": "投资(3.95%)",
      "target": "6xbKhMe7BqE",
      "source": "TCgLa3axRa0"
    },
    {
      "source": "0uAsYwSke3m0",
      "relation": "董事",
      "target": "IdLmpasckC0",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资(1.2231%)",
      "target": "6P5ur46WNJ3",
      "source": "T59LEFBJfuN"
    },
    {
      "source": "eTY9ThRVhpUJ",
      "relation": "董事",
      "target": "UluONnT3ZgE",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资(2.6572%)",
      "target": "kkXdAtmaXXj",
      "source": "CaD3Ax4bjx"
    },
    {
      "basetype": "line",
      "relation": "投资(1.2%)",
      "target": "I2xtd2KoRME",
      "source": "Ib2pEhALpf3"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "IGW5A8HwkWx"
    },
    {
      "basetype": "line",
      "relation": "投资(66.6669%)",
      "target": "3AlbTKjR33j",
      "source": "IdLmpasckC0"
    },
    {
      "basetype": "line",
      "relation": "投资(0.6622%)",
      "target": "BkEqfjgJnJ",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资(1.8505%)",
      "target": "MTUd7ED2Wfx",
      "source": "CaD3Ax4bjx"
    },
    {
      "source": "U70LNLlx2kJ",
      "relation": "董事",
      "target": "eTY9ThRVhpUJ",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资",
      "target": "Izto9m4ivXY",
      "source": "JYpcStI4qyj"
    },
    {
      "basetype": "line",
      "relation": "投资(0.85%)",
      "target": "6xbKhMe7BqE",
      "source": "TTsVVzhdhb0"
    },
    {
      "basetype": "line",
      "relation": "投资(20%)",
      "target": "TkIzYdXtJ7E",
      "source": "TCgLa3axRa0"
    },
    {
      "source": "CaD3Ax4bjx",
      "relation": "董事",
      "target": "HsOq4AuS5mN",
      "basetype": "line"
    },
    {
      "basetype": "line",
      "relation": "投资(0.6622%)",
      "target": "BkEqfjgJnJ",
      "source": "kkXdAtmaXXj"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "TCgLa3axRa0"
    },
    {
      "basetype": "best",
      "relation": "投资(33.538%)",
      "target": "U70LNLlx2kJ",
      "source": "LPI65UoS103"
    },
    {
      "basetype": "line",
      "relation": "投资(100%)",
      "target": "Ib2pEhALpf3",
      "source": "TCgLa3axRa0"
    },
    {
      "basetype": "line",
      "relation": "投资(2.2222%)",
      "target": "1FTTCDD8uFJ",
      "source": "IdLmpasckC0"
    },
    {
      "basetype": "line",
      "relation": "投资(83.5%)",
      "target": "eVu0hPk6mvCJ",
      "source": "BkEqfjgJnJ"
    },
    {
      "basetype": "best",
      "relation": "投资(1.2%)",
      "target": "I2xtd2KoRME",
      "source": "U70LNLlx2kJ"
    },
    {
      "basetype": "line",
      "relation": "投资(4%)",
      "target": "I2xtd2KoRME",
      "source": "Izto9m4ivXY"
    },
    {
      "basetype": "line",
      "relation": "投资(1.2%)",
      "target": "I2xtd2KoRME",
      "source": "3AlbTKjR33j"
    },
    {
      "basetype": "line",
      "relation": "投资(1.41%)",
      "target": "6xbKhMe7BqE",
      "source": "LPI65UoS103"
    }
  ],
  table:[
    {
      "status": "",
      "": "",
      "rowname": "路径-1",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 1,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 1
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 1,
      "conprop": "",
      "regionid": "上海市",
      "id": 2,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 1
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 1,
      "conprop": "1.2%",
      "regionid": "",
      "id": 3,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1500",
      "lerepsign": "",
      "position": "",
      "roadid": 1
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-资本投资服务-期货市场管理服务",
      "name": "永安期货股份有限公司",
      "parent": 1,
      "conprop": "",
      "regionid": "浙江省杭州市江干区",
      "id": 4,
      "regcap": "131000",
      "eid": "U70LNLlx2kJ",
      "esdate": "1992/9/7",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 1
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 1,
      "conprop": "33.53800190839695%",
      "regionid": "",
      "id": 5,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "43934.7825",
      "lerepsign": "",
      "position": "",
      "roadid": 1
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 1,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 6,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 1
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-2",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 7,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 2
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 7,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 8,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 2
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 7,
      "conprop": "33.53800190839695%",
      "regionid": "",
      "id": 9,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "43934.7825",
      "lerepsign": "",
      "position": "",
      "roadid": 2
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-资本投资服务-期货市场管理服务",
      "name": "永安期货股份有限公司",
      "parent": 7,
      "conprop": "",
      "regionid": "浙江省杭州市江干区",
      "id": 10,
      "regcap": "131000",
      "eid": "U70LNLlx2kJ",
      "esdate": "1992/9/7",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 2
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 7,
      "conprop": "1.2%",
      "regionid": "",
      "id": 11,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1500",
      "lerepsign": "",
      "position": "",
      "roadid": 2
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 7,
      "conprop": "",
      "regionid": "上海市",
      "id": 12,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 2
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-3",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 13,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 13,
      "conprop": "",
      "regionid": "上海市",
      "id": 14,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "4%",
      "regionid": "",
      "id": 15,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "国泰君安证券股份有限公司",
      "parent": 13,
      "conprop": "",
      "regionid": "上海市浦东新区",
      "id": 16,
      "regcap": "890794.7954",
      "eid": "TCgLa3axRa0",
      "esdate": "1999/8/18",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "0%",
      "regionid": "",
      "id": 17,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "上海证券有限责任公司",
      "parent": 13,
      "conprop": "",
      "regionid": "上海市黄浦区",
      "id": 18,
      "regcap": "532653.2",
      "eid": "TTsVVzhdhb0",
      "esdate": "2001/4/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "0.85%",
      "regionid": "",
      "id": 19,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "15",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-专用设备制造业-农、林、牧、渔专用机械制造-畜牧机械制造",
      "name": "吉林省艾斯克机电股份有限公司",
      "parent": 13,
      "conprop": "",
      "regionid": "吉林省四平市",
      "id": 20,
      "regcap": "1774",
      "eid": "6xbKhMe7BqE",
      "esdate": "1995/12/20",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "1.41%",
      "regionid": "",
      "id": 21,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "25",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 13,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 22,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 3
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-4",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 23,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 23,
      "conprop": "",
      "regionid": "上海市",
      "id": 24,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "4%",
      "regionid": "",
      "id": 25,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务",
      "name": "广发证券股份有限公司",
      "parent": 23,
      "conprop": "",
      "regionid": "广东省广州市天河区",
      "id": 26,
      "regcap": "762108.7664",
      "eid": "E8jD8W4h9nQ",
      "esdate": "1994/1/21",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "id": 27,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "总经理",
      "roadid": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "ntype": 4,
      "nicid": "",
      "name": "孙树明",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "id": 28,
      "regcap": "",
      "eid": "eN2zDr696r7Y",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "id": 29,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 4
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券市场管理服务",
      "name": "中证机构间报价系统股份有限公司",
      "parent": 23,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 30,
      "regcap": "755024.4469",
      "eid": "BkEqfjgJnJ",
      "esdate": "2013/2/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 31,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 23,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 32,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-5",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 33,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 33,
      "conprop": "",
      "regionid": "上海市",
      "id": 34,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "1.2%",
      "regionid": "",
      "id": 35,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1500",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-资本投资服务-期货市场管理服务",
      "name": "永安期货股份有限公司",
      "parent": 33,
      "conprop": "",
      "regionid": "浙江省杭州市江干区",
      "id": 36,
      "regcap": "131000",
      "eid": "U70LNLlx2kJ",
      "esdate": "1992/9/7",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "",
      "regionid": "",
      "id": 37,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 5
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "ntype": 4,
      "nicid": "",
      "name": "申建新",
      "parent": 33,
      "conprop": "",
      "regionid": "",
      "id": 38,
      "regcap": "",
      "eid": "eTY9ThRVhpUJ",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "",
      "regionid": "",
      "id": 39,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 5
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "浙江股权服务集团有限公司",
      "parent": 33,
      "conprop": "",
      "regionid": "浙江省杭州市江干区",
      "id": 40,
      "regcap": "70000",
      "eid": "UluONnT3ZgE",
      "esdate": "2012/9/3",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "8.857142857142858%",
      "regionid": "",
      "id": 41,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "6200",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 33,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 42,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 5
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-6",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 43,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 43,
      "conprop": "",
      "regionid": "上海市",
      "id": 44,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "2%",
      "regionid": "",
      "id": 45,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2500",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "租赁和商务服务业-商务服务业-其他商务服务业-其他未列明商务服务业",
      "name": "博时基金管理有限公司",
      "parent": 43,
      "conprop": "",
      "regionid": "广东省深圳市福田区",
      "id": 46,
      "regcap": "25000",
      "eid": "CJGlwMN0EE",
      "esdate": "1998/7/13",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "1.0701036888030433%",
      "regionid": "",
      "id": 47,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1300",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-金属制品业-其他金属制品制造-其他未列明金属制品制造",
      "name": "吉林利源精制股份有限公司",
      "parent": 43,
      "conprop": "",
      "regionid": "吉林省辽源市",
      "id": 48,
      "regcap": "121483.558",
      "eid": "6NZ3qksi3rx",
      "esdate": "2001/11/13",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "1.1112615229877758%",
      "regionid": "",
      "id": 49,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1350",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-其他金融业-金融信托与管理服务",
      "name": "财通基金管理有限公司",
      "parent": 43,
      "conprop": "",
      "regionid": "上海市虹口区",
      "id": 50,
      "regcap": "20000",
      "eid": "T59LEFBJfuN",
      "esdate": "2011/6/21",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "40%",
      "regionid": "",
      "id": 51,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "8000",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 43,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 52,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 6
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-7",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 53,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 53,
      "conprop": "",
      "regionid": "上海市",
      "id": 54,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "4%",
      "regionid": "",
      "id": 55,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-其他金融业-金融信托与管理服务-其他金融信托与管理服务",
      "name": "天弘基金管理有限公司",
      "parent": 53,
      "conprop": "",
      "regionid": "天津市静海区",
      "id": 56,
      "regcap": "51430",
      "eid": "eDvj4QIrXhi3",
      "esdate": "2004/11/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "2.2344871950410936%",
      "regionid": "",
      "id": 57,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2227.4325",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-计算机、通信和其他电子设备制造业-其他电子设备制造",
      "name": "宁波均胜电子股份有限公司",
      "parent": 53,
      "conprop": "",
      "regionid": "浙江省宁波市",
      "id": 58,
      "regcap": "136808.4624",
      "eid": "6P5ur46WNJ3",
      "esdate": "1992/8/7",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "1.2230877172523127%",
      "regionid": "",
      "id": 59,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1219.2262",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-其他金融业-金融信托与管理服务",
      "name": "财通基金管理有限公司",
      "parent": 53,
      "conprop": "",
      "regionid": "上海市虹口区",
      "id": 60,
      "regcap": "20000",
      "eid": "T59LEFBJfuN",
      "esdate": "2011/6/21",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "40%",
      "regionid": "",
      "id": 61,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "8000",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 53,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 62,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 7
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-8",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 63,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 63,
      "conprop": "",
      "regionid": "上海市",
      "id": 64,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "1.2%",
      "regionid": "",
      "id": 65,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1500",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-资本投资服务-其他期货市场服务",
      "name": "国泰君安期货有限公司",
      "parent": 63,
      "conprop": "",
      "regionid": "上海市静安区",
      "id": 66,
      "regcap": "300000",
      "eid": "Ib2pEhALpf3",
      "esdate": "2000/4/6",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "100%",
      "regionid": "",
      "id": 67,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "300000",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "国泰君安证券股份有限公司",
      "parent": 63,
      "conprop": "",
      "regionid": "上海市浦东新区",
      "id": 68,
      "regcap": "890794.7954",
      "eid": "TCgLa3axRa0",
      "esdate": "1999/8/18",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 69,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券市场管理服务",
      "name": "中证机构间报价系统股份有限公司",
      "parent": 63,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 70,
      "regcap": "755024.4469",
      "eid": "BkEqfjgJnJ",
      "esdate": "2013/2/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 71,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 63,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 72,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 8
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-9",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 73,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 73,
      "conprop": "",
      "regionid": "上海市",
      "id": 74,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "1.2%",
      "regionid": "",
      "id": 75,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1500",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-资本投资服务-其他期货市场服务",
      "name": "海通期货股份有限公司",
      "parent": 73,
      "conprop": "",
      "regionid": "上海市浦东新区",
      "id": 76,
      "regcap": "130150",
      "eid": "3AlbTKjR33j",
      "esdate": "1993/3/18",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "66.66692307692308%",
      "regionid": "",
      "id": 77,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "86667",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "海通证券股份有限公司",
      "parent": 73,
      "conprop": "",
      "regionid": "上海市黄浦区",
      "id": 78,
      "regcap": "1306420",
      "eid": "IdLmpasckC0",
      "esdate": "1993/2/2",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "2.2222222222222223%",
      "regionid": "",
      "id": 79,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "100",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-通用设备制造业-金属加工机械制造-金属成形机床制造",
      "name": "大连优创液压股份有限公司",
      "parent": 73,
      "conprop": "",
      "regionid": "辽宁省大连市甘井子区",
      "id": 80,
      "regcap": "4500",
      "eid": "1FTTCDD8uFJ",
      "esdate": "2004/4/23",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "2.2222222222222223%",
      "regionid": "",
      "id": 81,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "100",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 73,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 82,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 9
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-10",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 83,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 83,
      "conprop": "",
      "regionid": "上海市",
      "id": 84,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "4%",
      "regionid": "",
      "id": 85,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "中国银河证券股份有限公司",
      "parent": 83,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 86,
      "regcap": "1013725.8757",
      "eid": "CaD3Ax4bjx",
      "esdate": "2007/1/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "16.5%",
      "regionid": "",
      "id": 87,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "330",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "房地产业-房地产业-房地产开发经营",
      "name": "中证丽泽置业（北京）有限责任公司",
      "parent": 83,
      "conprop": "",
      "regionid": "北京市丰台区",
      "id": 88,
      "regcap": "2000",
      "eid": "eVu0hPk6mvCJ",
      "esdate": "2019/12/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "83.5%",
      "regionid": "",
      "id": 89,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1670",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券市场管理服务",
      "name": "中证机构间报价系统股份有限公司",
      "parent": 83,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 90,
      "regcap": "755024.4469",
      "eid": "BkEqfjgJnJ",
      "esdate": "2013/2/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 91,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 83,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 92,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 10
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-11",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 93,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 93,
      "conprop": "",
      "regionid": "上海市",
      "id": 94,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "2%",
      "regionid": "",
      "id": 95,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2500",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-其他金融业-金融信托与管理服务",
      "name": "华安基金管理有限公司",
      "parent": 93,
      "conprop": "",
      "regionid": "上海市",
      "id": 96,
      "regcap": "15000",
      "eid": "TkIzYdXtJ7E",
      "esdate": "1998/6/4",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "20%",
      "regionid": "",
      "id": 97,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "3000",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "国泰君安证券股份有限公司",
      "parent": 93,
      "conprop": "",
      "regionid": "上海市浦东新区",
      "id": 98,
      "regcap": "890794.7954",
      "eid": "TCgLa3axRa0",
      "esdate": "1999/8/18",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 99,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券市场管理服务",
      "name": "中证机构间报价系统股份有限公司",
      "parent": 93,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 100,
      "regcap": "755024.4469",
      "eid": "BkEqfjgJnJ",
      "esdate": "2013/2/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 101,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 93,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 102,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 11
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-12",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 103,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 103,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 104,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "1.41%",
      "regionid": "",
      "id": 105,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "25",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-专用设备制造业-农、林、牧、渔专用机械制造-畜牧机械制造",
      "name": "吉林省艾斯克机电股份有限公司",
      "parent": 103,
      "conprop": "",
      "regionid": "吉林省四平市",
      "id": 106,
      "regcap": "1774",
      "eid": "6xbKhMe7BqE",
      "esdate": "1995/12/20",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "3.95%",
      "regionid": "",
      "id": 107,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "70",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "国泰君安证券股份有限公司",
      "parent": 103,
      "conprop": "",
      "regionid": "上海市浦东新区",
      "id": 108,
      "regcap": "890794.7954",
      "eid": "TCgLa3axRa0",
      "esdate": "1999/8/18",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "100%",
      "regionid": "",
      "id": 109,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "300000",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-资本投资服务-其他期货市场服务",
      "name": "国泰君安期货有限公司",
      "parent": 103,
      "conprop": "",
      "regionid": "上海市静安区",
      "id": 110,
      "regcap": "300000",
      "eid": "Ib2pEhALpf3",
      "esdate": "2000/4/6",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "1.2%",
      "regionid": "",
      "id": 111,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1500",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 103,
      "conprop": "",
      "regionid": "上海市",
      "id": 112,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 12
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-13",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 113,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 113,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 114,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "2.2222222222222223%",
      "regionid": "",
      "id": 115,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "100",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-通用设备制造业-金属加工机械制造-金属成形机床制造",
      "name": "大连优创液压股份有限公司",
      "parent": 113,
      "conprop": "",
      "regionid": "辽宁省大连市甘井子区",
      "id": 116,
      "regcap": "4500",
      "eid": "1FTTCDD8uFJ",
      "esdate": "2004/4/23",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "2.2222222222222223%",
      "regionid": "",
      "id": 117,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "100",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "海通证券股份有限公司",
      "parent": 113,
      "conprop": "",
      "regionid": "上海市黄浦区",
      "id": 118,
      "regcap": "1306420",
      "eid": "IdLmpasckC0",
      "esdate": "1993/2/2",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "%",
      "regionid": "",
      "id": 119,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "申万宏源集团股份有限公司",
      "parent": 113,
      "conprop": "",
      "regionid": "新疆维吾尔自治区乌鲁木齐市",
      "id": 120,
      "regcap": "2503994.456",
      "eid": "Izto9m4ivXY",
      "esdate": "1996/9/16",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "4%",
      "regionid": "",
      "id": 121,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 113,
      "conprop": "",
      "regionid": "上海市",
      "id": 122,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 13
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-14",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 123,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 123,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 124,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 125,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券市场管理服务",
      "name": "中证机构间报价系统股份有限公司",
      "parent": 123,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 126,
      "regcap": "755024.4469",
      "eid": "BkEqfjgJnJ",
      "esdate": "2013/2/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 127,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-其他资本市场服务",
      "name": "东北证券股份有限公司",
      "parent": 123,
      "conprop": "",
      "regionid": "吉林省长春市",
      "id": 128,
      "regcap": "234045.2915",
      "eid": "kkXdAtmaXXj",
      "esdate": "1992/7/17",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "2.6571991087560196%",
      "regionid": "",
      "id": 129,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2600.29",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "中国银河证券股份有限公司",
      "parent": 123,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 130,
      "regcap": "1013725.8757",
      "eid": "CaD3Ax4bjx",
      "esdate": "2007/1/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "4%",
      "regionid": "",
      "id": 131,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 123,
      "conprop": "",
      "regionid": "上海市",
      "id": 132,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 14
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-15",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 133,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 133,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 134,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "%",
      "regionid": "",
      "id": 135,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "科学研究和技术服务业-科技推广和应用服务业-其他科技推广和应用服务业",
      "name": "北京仙果科技股份有限公司",
      "parent": 133,
      "conprop": "",
      "regionid": "北京市石景山区",
      "id": 136,
      "regcap": "5834",
      "eid": "7CXZjCRywcQ",
      "esdate": "2010/11/15",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "%",
      "regionid": "",
      "id": 137,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-其他资本市场服务",
      "name": "东北证券股份有限公司",
      "parent": 133,
      "conprop": "",
      "regionid": "吉林省长春市",
      "id": 138,
      "regcap": "234045.2915",
      "eid": "kkXdAtmaXXj",
      "esdate": "1992/7/17",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "2.6571991087560196%",
      "regionid": "",
      "id": 139,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2600.29",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "中国银河证券股份有限公司",
      "parent": 133,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 140,
      "regcap": "1013725.8757",
      "eid": "CaD3Ax4bjx",
      "esdate": "2007/1/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "4%",
      "regionid": "",
      "id": 141,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 133,
      "conprop": "",
      "regionid": "上海市",
      "id": 142,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 15
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-16",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 143,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 143,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 144,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "2.2222222222222223%",
      "regionid": "",
      "id": 145,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "100",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-通用设备制造业-金属加工机械制造-金属成形机床制造",
      "name": "大连优创液压股份有限公司",
      "parent": 143,
      "conprop": "",
      "regionid": "辽宁省大连市甘井子区",
      "id": 146,
      "regcap": "4500",
      "eid": "1FTTCDD8uFJ",
      "esdate": "2004/4/23",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "1.7777777777777777%",
      "regionid": "",
      "id": 147,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "80",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "方正证券股份有限公司",
      "parent": 143,
      "conprop": "",
      "regionid": "湖南省长沙市天心区",
      "id": 148,
      "regcap": "823210.1395",
      "eid": "JYpcStI4qyj",
      "esdate": "1994/10/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "%",
      "regionid": "",
      "id": 149,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "申万宏源集团股份有限公司",
      "parent": 143,
      "conprop": "",
      "regionid": "新疆维吾尔自治区乌鲁木齐市",
      "id": 150,
      "regcap": "2503994.456",
      "eid": "Izto9m4ivXY",
      "esdate": "1996/9/16",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "4%",
      "regionid": "",
      "id": 151,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 143,
      "conprop": "",
      "regionid": "上海市",
      "id": 152,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 16
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-17",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 153,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 153,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 154,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "40%",
      "regionid": "",
      "id": 155,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "8000",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-其他金融业-金融信托与管理服务",
      "name": "财通基金管理有限公司",
      "parent": 153,
      "conprop": "",
      "regionid": "上海市虹口区",
      "id": 156,
      "regcap": "20000",
      "eid": "T59LEFBJfuN",
      "esdate": "2011/6/21",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "id": 157,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 17
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "ntype": 4,
      "nicid": "",
      "name": "朱洪超",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "id": 158,
      "regcap": "",
      "eid": "0uAsYwSke3m0",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "id": 159,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 17
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "海通证券股份有限公司",
      "parent": 153,
      "conprop": "",
      "regionid": "上海市黄浦区",
      "id": 160,
      "regcap": "1306420",
      "eid": "IdLmpasckC0",
      "esdate": "1993/2/2",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "4%",
      "regionid": "",
      "id": 161,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 153,
      "conprop": "",
      "regionid": "上海市",
      "id": 162,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 17
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-18",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 163,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 163,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 164,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "40%",
      "regionid": "",
      "id": 165,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "8000",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-其他金融业-金融信托与管理服务",
      "name": "财通基金管理有限公司",
      "parent": 163,
      "conprop": "",
      "regionid": "上海市虹口区",
      "id": 166,
      "regcap": "20000",
      "eid": "T59LEFBJfuN",
      "esdate": "2011/6/21",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "1.1112615229877758%",
      "regionid": "",
      "id": 167,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1350",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-金属制品业-其他金属制品制造-其他未列明金属制品制造",
      "name": "吉林利源精制股份有限公司",
      "parent": 163,
      "conprop": "",
      "regionid": "吉林省辽源市",
      "id": 168,
      "regcap": "121483.558",
      "eid": "6NZ3qksi3rx",
      "esdate": "2001/11/13",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "1.0701036888030433%",
      "regionid": "",
      "id": 169,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1300",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "租赁和商务服务业-商务服务业-其他商务服务业-其他未列明商务服务业",
      "name": "博时基金管理有限公司",
      "parent": 163,
      "conprop": "",
      "regionid": "广东省深圳市福田区",
      "id": 170,
      "regcap": "25000",
      "eid": "CJGlwMN0EE",
      "esdate": "1998/7/13",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "2%",
      "regionid": "",
      "id": 171,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2500",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 163,
      "conprop": "",
      "regionid": "上海市",
      "id": 172,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 18
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-19",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 173,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 173,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 174,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "0.1371356175447171%",
      "regionid": "",
      "id": 175,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "16.6",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "制造业-医药制造业-中药饮片加工",
      "name": "安徽源和堂药业股份有限公司",
      "parent": 173,
      "conprop": "",
      "regionid": "安徽省亳州市涡阳县",
      "id": 176,
      "regcap": "17868.1296",
      "eid": "MTUd7ED2Wfx",
      "esdate": "2003/2/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "1.8505047186757002%",
      "regionid": "",
      "id": 177,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "224",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "中国银河证券股份有限公司",
      "parent": 173,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 178,
      "regcap": "1013725.8757",
      "eid": "CaD3Ax4bjx",
      "esdate": "2007/1/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "",
      "regionid": "",
      "id": 179,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "ntype": 4,
      "nicid": "",
      "name": "吴承明",
      "parent": 173,
      "conprop": "",
      "regionid": "",
      "id": 180,
      "regcap": "",
      "eid": "HsOq4AuS5mN",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "",
      "regionid": "",
      "id": 181,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "roadid": 19
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 173,
      "conprop": "",
      "regionid": "上海市",
      "id": 182,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-20",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "id": 183,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "财通证券股份有限公司",
      "parent": 183,
      "conprop": "",
      "regionid": "浙江省杭州市",
      "id": 184,
      "regcap": "358900",
      "eid": "LPI65UoS103",
      "esdate": "2003/6/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 185,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券市场管理服务",
      "name": "中证机构间报价系统股份有限公司",
      "parent": 183,
      "conprop": "",
      "regionid": "北京市西城区",
      "id": 186,
      "regcap": "755024.4469",
      "eid": "BkEqfjgJnJ",
      "esdate": "2013/2/27",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "0.6622302208595732%",
      "regionid": "",
      "id": 187,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-证券市场服务-证券经纪交易服务",
      "name": "东方证券股份有限公司",
      "parent": 183,
      "conprop": "",
      "regionid": "上海市黄浦区",
      "id": 188,
      "regcap": "699365.5803",
      "eid": "3Be4t06jbPQ",
      "esdate": "1997/12/10",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "35.41177110286756%",
      "regionid": "",
      "id": 189,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "4700",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "金融业-资本市场服务-期货市场服务-公开募集证券投资基金",
      "name": "汇添富基金管理股份有限公司",
      "parent": 183,
      "conprop": "",
      "regionid": "上海市黄浦区",
      "id": 190,
      "regcap": "13272.4224",
      "eid": "IGW5A8HwkWx",
      "esdate": "2005/2/3",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "4%",
      "regionid": "",
      "id": 191,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "5000",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "ntype": 1,
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发",
      "name": "证通股份有限公司",
      "parent": 183,
      "conprop": "",
      "regionid": "上海市",
      "id": 192,
      "regcap": "251875",
      "eid": "I2xtd2KoRME",
      "esdate": "2015/1/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "roadid": 20
    }
  ]
}