export default {
  nodes:[
    {
      "imgtype": "com",
      "num": 1,
      "basetype": "1",
      "name": "阿里云计算有限公司",
      "id": "CCUaVdXe6Jx"
    },
    {
      "imgtype": "com",
      "num": 2,
      "basetype": "1",
      "name": "蚂蚁科技集团股份有限公司",
      "id": "YnmrKTAvRwQ"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "武卫",
      "id": "B9rMPDFvT5s"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "冯云乐",
      "id": "mm05z5gyhI5Q"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "南昌传畅网络科技有限公司",
      "id": "efWPzMcpB25J"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "徐宏",
      "id": "mmlxbVXKv59Q"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "郑州阿里云计算有限公司",
      "id": "yJTF4QSTTjE"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "胡晓明",
      "id": "AZ0E9FLyJk0"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "蒋芳",
      "id": "cHUoPp5ksj3"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "杭州云铂投资咨询有限公司",
      "id": "CwogFAHHSSJ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "杭州君澳股权投资合伙企业（有限合伙）",
      "id": "L8Go5dftfPQ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "南京传泰物联网技术有限公司",
      "id": "ebdTBDlTYuVQ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "杭州同欣网络技术有限公司",
      "id": "ePUDb2GgZb20"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "张勇",
      "id": "EEZVQLSuGYx"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "杭州臻希投资管理有限公司",
      "id": "eTiTjxEA2zZx"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "浙江淘宝网络有限公司",
      "id": "U6j8zLw04SN"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "阿里（四川）网络技术有限公司",
      "id": "eIwQiNzNvrx3"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "浙江数蜂科技有限公司",
      "id": "eCTrMiiWQIvj"
    },
    {
      "imgtype": "man",
      "basetype": "4",
      "name": "张建锋",
      "id": "eJ4qXDo9aWts"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "阿里巴巴（中国）有限公司",
      "id": "v3r8ujwhaTY"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "浙江天猫网络有限公司",
      "id": "UvCm1v3O5rE"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "浙江天猫技术有限公司",
      "id": "YWbY35V5F0Y"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "淘宝（中国）软件有限公司",
      "id": "YankUsvZjPs"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "上海云鑫创业投资有限公司",
      "id": "TdiXw5qAqCs"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "杭州信投信息技术有限公司",
      "id": "eoGgveZR89aJ"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "杭州阿里巴巴网络科技有限公司",
      "id": "ePqkaoDOvccs"
    },
    {
      "imgtype": "com",
      "basetype": "1",
      "name": "中联京华文化传播（北京）有限公司",
      "id": "y3bFi1LWos"
    }
  ],
  edges:[
    {
      "source": "cHUoPp5ksj3",
      "relation": "执行董事兼总经理",
      "target": "CwogFAHHSSJ",
      "basetype": "line"
    },
    {
      "source": "AZ0E9FLyJk0",
      "relation": "总经理",
      "target": "YnmrKTAvRwQ",
      "basetype": "line"
    },
    {
      "source": "v3r8ujwhaTY",
      "relation": "董事",
      "target": "cHUoPp5ksj3",
      "basetype": "line"
    },
    {
      "source": "ePUDb2GgZb20",
      "relation": "董事长兼总经理",
      "target": "EEZVQLSuGYx",
      "basetype": "line"
    },
    {
      "relation": "投资(50%)",
      "basetype": "line",
      "target": "y3bFi1LWos",
      "source": "EEZVQLSuGYx"
    },
    {
      "source": "B9rMPDFvT5s",
      "relation": "董事",
      "target": "v3r8ujwhaTY",
      "basetype": "line"
    },
    {
      "source": "mm05z5gyhI5Q",
      "relation": "监事",
      "target": "yJTF4QSTTjE",
      "basetype": "line"
    },
    {
      "source": "eoGgveZR89aJ",
      "relation": "监事",
      "target": "mm05z5gyhI5Q",
      "basetype": "line"
    },
    {
      "relation": "投资(50%)",
      "basetype": "line",
      "target": "y3bFi1LWos",
      "source": "cHUoPp5ksj3"
    },
    {
      "relation": "投资(34.15%)",
      "basetype": "line",
      "target": "YnmrKTAvRwQ",
      "source": "L8Go5dftfPQ"
    },
    {
      "source": "yJTF4QSTTjE",
      "relation": "执行董事兼总经理",
      "target": "AZ0E9FLyJk0",
      "basetype": "line"
    },
    {
      "source": "B9rMPDFvT5s",
      "relation": "董事",
      "target": "ePqkaoDOvccs",
      "basetype": "line"
    },
    {
      "source": "EEZVQLSuGYx",
      "relation": "",
      "target": "YnmrKTAvRwQ",
      "basetype": "line"
    },
    {
      "source": "CCUaVdXe6Jx",
      "relation": "董事",
      "target": "B9rMPDFvT5s",
      "basetype": "best"
    },
    {
      "source": "ebdTBDlTYuVQ",
      "relation": "董事",
      "target": "mmlxbVXKv59Q",
      "basetype": "line"
    },
    {
      "source": "EEZVQLSuGYx",
      "relation": "董事长兼总经理",
      "target": "YankUsvZjPs",
      "basetype": "line"
    },
    {
      "source": "efWPzMcpB25J",
      "relation": "董事",
      "target": "mmlxbVXKv59Q",
      "basetype": "line"
    },
    {
      "source": "mm05z5gyhI5Q",
      "relation": "监事",
      "target": "ebdTBDlTYuVQ",
      "basetype": "line"
    },
    {
      "source": "mm05z5gyhI5Q",
      "relation": "",
      "target": "eIwQiNzNvrx3",
      "basetype": "line"
    },
    {
      "source": "CCUaVdXe6Jx",
      "relation": "董事",
      "target": "cHUoPp5ksj3",
      "basetype": "line"
    },
    {
      "source": "mm05z5gyhI5Q",
      "relation": "监事",
      "target": "ePUDb2GgZb20",
      "basetype": "line"
    },
    {
      "relation": "投资(0.1776%)",
      "basetype": "line",
      "target": "L8Go5dftfPQ",
      "source": "eJ4qXDo9aWts"
    },
    {
      "relation": "投资(100%)",
      "basetype": "line",
      "target": "TdiXw5qAqCs",
      "source": "YnmrKTAvRwQ"
    },
    {
      "source": "CCUaVdXe6Jx",
      "relation": "监事",
      "target": "mm05z5gyhI5Q",
      "basetype": "line"
    },
    {
      "relation": "投资(42.4801%)",
      "basetype": "line",
      "target": "eoGgveZR89aJ",
      "source": "TdiXw5qAqCs"
    },
    {
      "source": "B9rMPDFvT5s",
      "relation": "董事",
      "target": "YWbY35V5F0Y",
      "basetype": "line"
    },
    {
      "relation": "投资(100%)",
      "basetype": "line",
      "target": "eCTrMiiWQIvj",
      "source": "CCUaVdXe6Jx"
    },
    {
      "source": "mm05z5gyhI5Q",
      "relation": "监事",
      "target": "efWPzMcpB25J",
      "basetype": "line"
    },
    {
      "source": "eIwQiNzNvrx3",
      "relation": "监事",
      "target": "mmlxbVXKv59Q",
      "basetype": "line"
    },
    {
      "source": "B9rMPDFvT5s",
      "relation": "",
      "target": "YnmrKTAvRwQ",
      "basetype": "best"
    },
    {
      "relation": "投资(0.0438%)",
      "basetype": "line",
      "target": "L8Go5dftfPQ",
      "source": "CwogFAHHSSJ"
    },
    {
      "source": "YWbY35V5F0Y",
      "relation": "董事",
      "target": "cHUoPp5ksj3",
      "basetype": "line"
    },
    {
      "source": "U6j8zLw04SN",
      "relation": "股东代表监事",
      "target": "B9rMPDFvT5s",
      "basetype": "line"
    },
    {
      "source": "YankUsvZjPs",
      "relation": "董事",
      "target": "cHUoPp5ksj3",
      "basetype": "line"
    },
    {
      "relation": "投资(100%)",
      "basetype": "line",
      "target": "U6j8zLw04SN",
      "source": "eTiTjxEA2zZx"
    },
    {
      "relation": "投资(100%)",
      "basetype": "line",
      "target": "UvCm1v3O5rE",
      "source": "eTiTjxEA2zZx"
    },
    {
      "relation": "投资(100%)",
      "basetype": "line",
      "target": "CCUaVdXe6Jx",
      "source": "eTiTjxEA2zZx"
    },
    {
      "source": "eCTrMiiWQIvj",
      "relation": "执行董事兼总经理",
      "target": "eJ4qXDo9aWts",
      "basetype": "line"
    },
    {
      "source": "ePqkaoDOvccs",
      "relation": "董事",
      "target": "cHUoPp5ksj3",
      "basetype": "line"
    },
    {
      "source": "v3r8ujwhaTY",
      "relation": "董事长兼总经理",
      "target": "EEZVQLSuGYx",
      "basetype": "line"
    },
    {
      "source": "B9rMPDFvT5s",
      "relation": "董事",
      "target": "UvCm1v3O5rE",
      "basetype": "line"
    },
    {
      "source": "mmlxbVXKv59Q",
      "relation": "监事",
      "target": "YnmrKTAvRwQ",
      "basetype": "line"
    }
  ],
  table:[
    {
      "status": "",
      "": "",
      "rowname": "路径-1",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 1,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 1
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 1,
      "conprop": "",
      "ntype": 1,
      "roadid": 1,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 2
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 1,
      "conprop": "",
      "regionid": "",
      "roadid": 1,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 3
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 1,
      "conprop": "",
      "ntype": 4,
      "roadid": 1,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 4
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 1,
      "conprop": "",
      "regionid": "",
      "roadid": 1,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 5
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 1,
      "conprop": "",
      "ntype": 1,
      "roadid": 1,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 6
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-2",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 2,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 7
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 7,
      "conprop": "",
      "ntype": 1,
      "roadid": 2,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 8
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 7,
      "conprop": "",
      "regionid": "",
      "roadid": 2,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 9
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 7,
      "conprop": "",
      "ntype": 4,
      "roadid": 2,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 10
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 7,
      "conprop": "",
      "regionid": "",
      "roadid": 2,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 11
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 7,
      "conprop": "",
      "ntype": 1,
      "roadid": 2,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 12
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-3",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 3,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 13
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 13,
      "conprop": "",
      "ntype": 1,
      "roadid": 3,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 14
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "",
      "regionid": "",
      "roadid": 3,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 15
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 13,
      "conprop": "",
      "ntype": 4,
      "roadid": 3,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 16
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "",
      "regionid": "",
      "roadid": 3,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 17
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "江西省南昌市南昌县",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-基础软件开发",
      "name": "南昌传畅网络科技有限公司",
      "parent": 13,
      "conprop": "",
      "ntype": 1,
      "roadid": 3,
      "regcap": "10000",
      "eid": "efWPzMcpB25J",
      "esdate": "2020/7/24",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 18
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "",
      "regionid": "",
      "roadid": 3,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 19
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "徐宏",
      "parent": 13,
      "conprop": "",
      "ntype": 4,
      "roadid": 3,
      "regcap": "",
      "eid": "mmlxbVXKv59Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 20
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 13,
      "conprop": "",
      "regionid": "",
      "roadid": 3,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 21
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 13,
      "conprop": "",
      "ntype": 1,
      "roadid": 3,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 22
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-4",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 4,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 23
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 23,
      "conprop": "",
      "ntype": 1,
      "roadid": 4,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 24
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "roadid": 4,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 25
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 23,
      "conprop": "",
      "ntype": 4,
      "roadid": 4,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 26
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "roadid": 4,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 27
    },
    {
      "status": "注销",
      "": "",
      "rowname": "企业",
      "regionid": "河南省郑州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-其他信息技术服务业-其他未列明信息技术服务业",
      "name": "郑州阿里云计算有限公司",
      "parent": 23,
      "conprop": "",
      "ntype": 1,
      "roadid": 4,
      "regcap": "1000",
      "eid": "yJTF4QSTTjE",
      "esdate": "2015/11/24",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 28
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "roadid": 4,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "执行董事兼总经理",
      "id": 29
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "胡晓明",
      "parent": 23,
      "conprop": "",
      "ntype": 4,
      "roadid": 4,
      "regcap": "",
      "eid": "AZ0E9FLyJk0",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 30
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 23,
      "conprop": "",
      "regionid": "",
      "roadid": 4,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "总经理",
      "id": 31
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 23,
      "conprop": "",
      "ntype": 1,
      "roadid": 4,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 32
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-5",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 5,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 33
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 33,
      "conprop": "",
      "ntype": 1,
      "roadid": 5,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 34
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "",
      "regionid": "",
      "roadid": 5,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 35
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "蒋芳",
      "parent": 33,
      "conprop": "",
      "ntype": 4,
      "roadid": 5,
      "regcap": "",
      "eid": "cHUoPp5ksj3",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 36
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "",
      "regionid": "",
      "roadid": 5,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "执行董事兼总经理",
      "id": 37
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "杭州云铂投资咨询有限公司",
      "parent": 33,
      "conprop": "",
      "ntype": 1,
      "roadid": 5,
      "regcap": "1010",
      "eid": "CwogFAHHSSJ",
      "esdate": "2012/10/22",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 38
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "0.04379064045125379%",
      "regionid": "",
      "roadid": 5,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "500",
      "lerepsign": "",
      "position": "",
      "id": 39
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "杭州君澳股权投资合伙企业（有限合伙）",
      "parent": 33,
      "conprop": "",
      "ntype": 1,
      "roadid": 5,
      "regcap": "0",
      "eid": "L8Go5dftfPQ",
      "esdate": "2012/12/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 40
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 33,
      "conprop": "34.14997076666666%",
      "regionid": "",
      "roadid": 5,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "512249.5615",
      "lerepsign": "",
      "position": "",
      "id": 41
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 33,
      "conprop": "",
      "ntype": 1,
      "roadid": 5,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 42
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-6",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 6,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 43
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 43,
      "conprop": "",
      "ntype": 1,
      "roadid": 6,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 44
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "",
      "regionid": "",
      "roadid": 6,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 45
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 43,
      "conprop": "",
      "ntype": 4,
      "roadid": 6,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 46
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "",
      "regionid": "",
      "roadid": 6,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 47
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "江苏省",
      "nicid": "科学研究和技术服务业-研究和试验发展",
      "name": "南京传泰物联网技术有限公司",
      "parent": 43,
      "conprop": "",
      "ntype": 1,
      "roadid": 6,
      "regcap": "35000",
      "eid": "ebdTBDlTYuVQ",
      "esdate": "2020/4/28",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 48
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "",
      "regionid": "",
      "roadid": 6,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 49
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "徐宏",
      "parent": 43,
      "conprop": "",
      "ntype": 4,
      "roadid": 6,
      "regcap": "",
      "eid": "mmlxbVXKv59Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 50
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 43,
      "conprop": "",
      "regionid": "",
      "roadid": 6,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 51
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 43,
      "conprop": "",
      "ntype": 1,
      "roadid": 6,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 52
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-7",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 7,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 53
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 53,
      "conprop": "",
      "ntype": 1,
      "roadid": 7,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 54
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "",
      "regionid": "",
      "roadid": 7,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 55
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 53,
      "conprop": "",
      "ntype": 4,
      "roadid": 7,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 56
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "",
      "regionid": "",
      "roadid": 7,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 57
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "杭州同欣网络技术有限公司",
      "parent": 53,
      "conprop": "",
      "ntype": 1,
      "roadid": 7,
      "regcap": "1220000",
      "eid": "ePUDb2GgZb20",
      "esdate": "2018/3/1",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 58
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "",
      "regionid": "",
      "roadid": 7,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "董事长兼总经理",
      "id": 59
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张勇",
      "parent": 53,
      "conprop": "",
      "ntype": 4,
      "roadid": 7,
      "regcap": "",
      "eid": "EEZVQLSuGYx",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 60
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 53,
      "conprop": "",
      "regionid": "",
      "roadid": 7,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 61
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 53,
      "conprop": "",
      "ntype": 1,
      "roadid": 7,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 62
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-8",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 8,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 63
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 63,
      "conprop": "",
      "ntype": 1,
      "roadid": 8,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 64
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "100%",
      "regionid": "",
      "roadid": 8,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 65
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "杭州臻希投资管理有限公司",
      "parent": 63,
      "conprop": "",
      "ntype": 1,
      "roadid": 8,
      "regcap": "500",
      "eid": "eTiTjxEA2zZx",
      "esdate": "2017/11/10",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 66
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "100%",
      "regionid": "",
      "roadid": 8,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 67
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "浙江淘宝网络有限公司",
      "parent": 63,
      "conprop": "",
      "ntype": 1,
      "roadid": 8,
      "regcap": "6500",
      "eid": "U6j8zLw04SN",
      "esdate": "2003/9/4",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 68
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "",
      "regionid": "",
      "roadid": 8,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "股东代表监事",
      "id": 69
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 63,
      "conprop": "",
      "ntype": 4,
      "roadid": 8,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 70
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 63,
      "conprop": "",
      "regionid": "",
      "roadid": 8,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 71
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 63,
      "conprop": "",
      "ntype": 1,
      "roadid": 8,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 72
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-9",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 9,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 73
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 73,
      "conprop": "",
      "ntype": 1,
      "roadid": 9,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 74
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "",
      "regionid": "",
      "roadid": 9,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 75
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 73,
      "conprop": "",
      "ntype": 4,
      "roadid": 9,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 76
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "",
      "regionid": "",
      "roadid": 9,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 77
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "四川省",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-其他信息技术服务业-其他未列明信息技术服务业",
      "name": "阿里（四川）网络技术有限公司",
      "parent": 73,
      "conprop": "",
      "ntype": 1,
      "roadid": 9,
      "regcap": "5000",
      "eid": "eIwQiNzNvrx3",
      "esdate": "2017/10/12",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 78
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "",
      "regionid": "",
      "roadid": 9,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 79
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "徐宏",
      "parent": 73,
      "conprop": "",
      "ntype": 4,
      "roadid": 9,
      "regcap": "",
      "eid": "mmlxbVXKv59Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 80
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 73,
      "conprop": "",
      "regionid": "",
      "roadid": 9,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 81
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 73,
      "conprop": "",
      "ntype": 1,
      "roadid": 9,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 82
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-10",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 10,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 83
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 83,
      "conprop": "",
      "ntype": 1,
      "roadid": 10,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 84
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "100%",
      "regionid": "",
      "roadid": 10,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2000",
      "lerepsign": "",
      "position": "",
      "id": 85
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-互联网和相关服务-其他互联网服务",
      "name": "浙江数蜂科技有限公司",
      "parent": 83,
      "conprop": "",
      "ntype": 1,
      "roadid": 10,
      "regcap": "2000",
      "eid": "eCTrMiiWQIvj",
      "esdate": "2018/10/17",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 86
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "",
      "regionid": "",
      "roadid": 10,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "执行董事兼总经理",
      "id": 87
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张建锋",
      "parent": 83,
      "conprop": "",
      "ntype": 4,
      "roadid": 10,
      "regcap": "",
      "eid": "eJ4qXDo9aWts",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 88
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "0.1776303395570051%",
      "regionid": "",
      "roadid": 10,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "2028.177",
      "lerepsign": "",
      "position": "",
      "id": 89
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "杭州君澳股权投资合伙企业（有限合伙）",
      "parent": 83,
      "conprop": "",
      "ntype": 1,
      "roadid": 10,
      "regcap": "0",
      "eid": "L8Go5dftfPQ",
      "esdate": "2012/12/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 90
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 83,
      "conprop": "34.14997076666666%",
      "regionid": "",
      "roadid": 10,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "512249.5615",
      "lerepsign": "",
      "position": "",
      "id": 91
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 83,
      "conprop": "",
      "ntype": 1,
      "roadid": 10,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 92
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-11",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 11,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 93
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 93,
      "conprop": "",
      "ntype": 1,
      "roadid": 11,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 94
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "",
      "regionid": "",
      "roadid": 11,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 95
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 93,
      "conprop": "",
      "ntype": 4,
      "roadid": 11,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 96
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "",
      "regionid": "",
      "roadid": 11,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 97
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市滨江区",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-其他企业管理服务",
      "name": "阿里巴巴（中国）有限公司",
      "parent": 93,
      "conprop": "",
      "ntype": 1,
      "roadid": 11,
      "regcap": "15298",
      "eid": "v3r8ujwhaTY",
      "esdate": "2007/3/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 98
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "",
      "regionid": "",
      "roadid": 11,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "董事长兼总经理",
      "id": 99
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张勇",
      "parent": 93,
      "conprop": "",
      "ntype": 4,
      "roadid": 11,
      "regcap": "",
      "eid": "EEZVQLSuGYx",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 100
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 93,
      "conprop": "",
      "regionid": "",
      "roadid": 11,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 101
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 93,
      "conprop": "",
      "ntype": 1,
      "roadid": 11,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 102
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-12",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 12,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 103
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 103,
      "conprop": "",
      "ntype": 1,
      "roadid": 12,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 104
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "",
      "regionid": "",
      "roadid": 12,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 105
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 103,
      "conprop": "",
      "ntype": 4,
      "roadid": 12,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 106
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "",
      "regionid": "",
      "roadid": 12,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 107
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "科学研究和技术服务业-科技推广和应用服务业-其他科技推广和应用服务业",
      "name": "浙江天猫网络有限公司",
      "parent": 103,
      "conprop": "",
      "ntype": 1,
      "roadid": 12,
      "regcap": "1000",
      "eid": "UvCm1v3O5rE",
      "esdate": "2011/3/28",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 108
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "100%",
      "regionid": "",
      "roadid": 12,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "1000",
      "lerepsign": "",
      "position": "",
      "id": 109
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "杭州臻希投资管理有限公司",
      "parent": 103,
      "conprop": "",
      "ntype": 1,
      "roadid": 12,
      "regcap": "500",
      "eid": "eTiTjxEA2zZx",
      "esdate": "2017/11/10",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 110
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 103,
      "conprop": "100%",
      "regionid": "",
      "roadid": 12,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 111
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 103,
      "conprop": "",
      "ntype": 1,
      "roadid": 12,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 112
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-13",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 13,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 113
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 113,
      "conprop": "",
      "ntype": 1,
      "roadid": 13,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 114
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "",
      "regionid": "",
      "roadid": 13,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 115
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 113,
      "conprop": "",
      "ntype": 4,
      "roadid": 13,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 116
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "",
      "regionid": "",
      "roadid": 13,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 117
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "浙江天猫技术有限公司",
      "parent": 113,
      "conprop": "",
      "ntype": 1,
      "roadid": 13,
      "regcap": "11400",
      "eid": "YWbY35V5F0Y",
      "esdate": "2010/10/25",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 118
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "",
      "regionid": "",
      "roadid": 13,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 119
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "蒋芳",
      "parent": 113,
      "conprop": "",
      "ntype": 4,
      "roadid": 13,
      "regcap": "",
      "eid": "cHUoPp5ksj3",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 120
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 113,
      "conprop": "",
      "regionid": "",
      "roadid": 13,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 121
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 113,
      "conprop": "",
      "ntype": 1,
      "roadid": 13,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 122
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-14",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 14,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 123
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 123,
      "conprop": "",
      "ntype": 1,
      "roadid": 14,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 124
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "",
      "regionid": "",
      "roadid": 14,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 125
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张勇",
      "parent": 123,
      "conprop": "",
      "ntype": 4,
      "roadid": 14,
      "regcap": "",
      "eid": "EEZVQLSuGYx",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 126
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "",
      "regionid": "",
      "roadid": 14,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "董事长兼总经理",
      "id": 127
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "淘宝（中国）软件有限公司",
      "parent": 123,
      "conprop": "",
      "ntype": 1,
      "roadid": 14,
      "regcap": "37500",
      "eid": "YankUsvZjPs",
      "esdate": "2004/12/7",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 128
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "",
      "regionid": "",
      "roadid": 14,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 129
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "蒋芳",
      "parent": 123,
      "conprop": "",
      "ntype": 4,
      "roadid": 14,
      "regcap": "",
      "eid": "cHUoPp5ksj3",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 130
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 123,
      "conprop": "",
      "regionid": "",
      "roadid": 14,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 131
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 123,
      "conprop": "",
      "ntype": 1,
      "roadid": 14,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 132
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-15",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 15,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 133
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 133,
      "conprop": "",
      "ntype": 1,
      "roadid": 15,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 134
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "99.99999946617343%",
      "regionid": "",
      "roadid": 15,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "145178.2336",
      "lerepsign": "",
      "position": "",
      "id": 135
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "上海市黄浦区",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-投资与资产管理",
      "name": "上海云鑫创业投资有限公司",
      "parent": 133,
      "conprop": "",
      "ntype": 1,
      "roadid": 15,
      "regcap": "145178.2336",
      "eid": "TdiXw5qAqCs",
      "esdate": "2014/2/11",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 136
    },
    {
      "status": "",
      "": "",
      "rowname": "投资",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "42.48014204428264%",
      "regionid": "",
      "roadid": 15,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "7.3853",
      "lerepsign": "",
      "position": "",
      "id": 137
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "杭州信投信息技术有限公司",
      "parent": 133,
      "conprop": "",
      "ntype": 1,
      "roadid": 15,
      "regcap": "17.3853",
      "eid": "eoGgveZR89aJ",
      "esdate": "2019/10/24",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 138
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "",
      "regionid": "",
      "roadid": 15,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 139
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 133,
      "conprop": "",
      "ntype": 4,
      "roadid": 15,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 140
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 133,
      "conprop": "",
      "regionid": "",
      "roadid": 15,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 141
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 133,
      "conprop": "",
      "ntype": 1,
      "roadid": 15,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 142
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-16",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 16,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 143
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 143,
      "conprop": "",
      "ntype": 1,
      "roadid": 16,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 144
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "",
      "regionid": "",
      "roadid": 16,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 145
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张勇",
      "parent": 143,
      "conprop": "",
      "ntype": 4,
      "roadid": 16,
      "regcap": "",
      "eid": "EEZVQLSuGYx",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 146
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "",
      "regionid": "",
      "roadid": 16,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "董事长兼总经理",
      "id": 147
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市滨江区",
      "nicid": "租赁和商务服务业-商务服务业-企业管理服务-其他企业管理服务",
      "name": "阿里巴巴（中国）有限公司",
      "parent": 143,
      "conprop": "",
      "ntype": 1,
      "roadid": 16,
      "regcap": "15298",
      "eid": "v3r8ujwhaTY",
      "esdate": "2007/3/26",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 148
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "",
      "regionid": "",
      "roadid": 16,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 149
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "蒋芳",
      "parent": 143,
      "conprop": "",
      "ntype": 4,
      "roadid": 16,
      "regcap": "",
      "eid": "cHUoPp5ksj3",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 150
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 143,
      "conprop": "",
      "regionid": "",
      "roadid": 16,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 151
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 143,
      "conprop": "",
      "ntype": 1,
      "roadid": 16,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 152
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-17",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 17,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 153
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 153,
      "conprop": "",
      "ntype": 1,
      "roadid": 17,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 154
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "roadid": 17,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 155
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "徐宏",
      "parent": 153,
      "conprop": "",
      "ntype": 4,
      "roadid": 17,
      "regcap": "",
      "eid": "mmlxbVXKv59Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 156
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "roadid": 17,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 157
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "江苏省",
      "nicid": "科学研究和技术服务业-研究和试验发展",
      "name": "南京传泰物联网技术有限公司",
      "parent": 153,
      "conprop": "",
      "ntype": 1,
      "roadid": 17,
      "regcap": "35000",
      "eid": "ebdTBDlTYuVQ",
      "esdate": "2020/4/28",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 158
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "roadid": 17,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 159
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 153,
      "conprop": "",
      "ntype": 4,
      "roadid": 17,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 160
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 153,
      "conprop": "",
      "regionid": "",
      "roadid": 17,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 161
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 153,
      "conprop": "",
      "ntype": 1,
      "roadid": 17,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 162
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-18",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 18,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 163
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 163,
      "conprop": "",
      "ntype": 1,
      "roadid": 18,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 164
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "",
      "regionid": "",
      "roadid": 18,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 165
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "武卫",
      "parent": 163,
      "conprop": "",
      "ntype": 4,
      "roadid": 18,
      "regcap": "",
      "eid": "B9rMPDFvT5s",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 166
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "",
      "regionid": "",
      "roadid": 18,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 167
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "科学研究和技术服务业-科技推广和应用服务业-其他科技推广和应用服务业",
      "name": "杭州阿里巴巴网络科技有限公司",
      "parent": 163,
      "conprop": "",
      "ntype": 1,
      "roadid": 18,
      "regcap": "1220000",
      "eid": "ePqkaoDOvccs",
      "esdate": "2018/3/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 168
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "",
      "regionid": "",
      "roadid": 18,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 169
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "蒋芳",
      "parent": 163,
      "conprop": "",
      "ntype": 4,
      "roadid": 18,
      "regcap": "",
      "eid": "cHUoPp5ksj3",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 170
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 163,
      "conprop": "",
      "regionid": "",
      "roadid": 18,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 171
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 163,
      "conprop": "",
      "ntype": 1,
      "roadid": 18,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 172
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-19",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 19,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 173
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 173,
      "conprop": "",
      "ntype": 1,
      "roadid": 19,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 174
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "",
      "regionid": "",
      "roadid": 19,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 175
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张勇",
      "parent": 173,
      "conprop": "",
      "ntype": 4,
      "roadid": 19,
      "regcap": "",
      "eid": "EEZVQLSuGYx",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 176
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "50%",
      "regionid": "",
      "roadid": 19,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "500",
      "lerepsign": "",
      "position": "",
      "id": 177
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "北京市朝阳区",
      "nicid": "文化、体育和娱乐业-体育-其他体育",
      "name": "中联京华文化传播（北京）有限公司",
      "parent": 173,
      "conprop": "",
      "ntype": 1,
      "roadid": 19,
      "regcap": "1000",
      "eid": "y3bFi1LWos",
      "esdate": "2005/6/24",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 178
    },
    {
      "status": "",
      "": "",
      "rowname": "股东",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "50%",
      "regionid": "",
      "roadid": 19,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "500",
      "lerepsign": "",
      "position": "",
      "id": 179
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "蒋芳",
      "parent": 173,
      "conprop": "",
      "ntype": 4,
      "roadid": 19,
      "regcap": "",
      "eid": "cHUoPp5ksj3",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 180
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 173,
      "conprop": "",
      "regionid": "",
      "roadid": 19,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "董事",
      "id": 181
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 173,
      "conprop": "",
      "ntype": 1,
      "roadid": 19,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 182
    },
    {
      "status": "",
      "": "",
      "rowname": "路径-20",
      "nicid": "",
      "name": "",
      "parent": "",
      "conprop": "",
      "regionid": "",
      "roadid": 20,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 183
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市西湖区",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-信息技术咨询服务-信息系统集成服务",
      "name": "蚂蚁科技集团股份有限公司",
      "parent": 183,
      "conprop": "",
      "ntype": 1,
      "roadid": 20,
      "regcap": "2377862.9496",
      "eid": "YnmrKTAvRwQ",
      "esdate": "2000/10/19",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 184
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "",
      "regionid": "",
      "roadid": 20,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "",
      "id": 185
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "张勇",
      "parent": 183,
      "conprop": "",
      "ntype": 4,
      "roadid": 20,
      "regcap": "",
      "eid": "EEZVQLSuGYx",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 186
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "",
      "regionid": "",
      "roadid": 20,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "是",
      "position": "董事长兼总经理",
      "id": 187
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "杭州同欣网络技术有限公司",
      "parent": 183,
      "conprop": "",
      "ntype": 1,
      "roadid": 20,
      "regcap": "1220000",
      "eid": "ePUDb2GgZb20",
      "esdate": "2018/3/1",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 188
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "",
      "regionid": "",
      "roadid": 20,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 189
    },
    {
      "status": "",
      "": "",
      "rowname": "个人",
      "regionid": "",
      "nicid": "",
      "name": "冯云乐",
      "parent": 183,
      "conprop": "",
      "ntype": 4,
      "roadid": 20,
      "regcap": "",
      "eid": "mm05z5gyhI5Q",
      "esdate": "",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 190
    },
    {
      "status": "",
      "": "",
      "rowname": "任职",
      "nicid": "",
      "name": "",
      "parent": 183,
      "conprop": "",
      "regionid": "",
      "roadid": 20,
      "regcap": "",
      "eid": "",
      "esdate": "",
      "conam": "",
      "lerepsign": "否",
      "position": "监事",
      "id": 191
    },
    {
      "status": "在营",
      "": "",
      "rowname": "企业",
      "regionid": "浙江省杭州市",
      "nicid": "信息传输、软件和信息技术服务业-软件和信息技术服务业-软件开发-应用软件开发",
      "name": "阿里云计算有限公司",
      "parent": 183,
      "conprop": "",
      "ntype": 1,
      "roadid": 20,
      "regcap": "100000",
      "eid": "CCUaVdXe6Jx",
      "esdate": "2008/4/8",
      "conam": "",
      "lerepsign": "",
      "position": "",
      "id": 192
    }
  ]
}